# Generated by Django 2.0 on 2021-08-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='sex',
            field=models.CharField(default='男', max_length=2, verbose_name='性别'),
        ),
    ]
